export * from "./CreatePersonQuery";
export * from "./CreatePersonResponse";
export * from "./GetMyOwnDetailsResponse";
export * from "./GetPersonDetailQuery";
export * from "./GetPersonDetailResponse";
export * from "./ListPeopleQuery";
export * from "./ListPeopleResponse";
export * from "./UpdatePersonQuery";
export * from "./UpdatePersonResponse";